name: Hourly Feature Pipeline

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests pandas pyarrow python-dotenv

      - name: Run Feature Pipeline
        env:
          OPENAQ_API_KEY: ${{ secrets.OPENAQ_API_KEY }}
        run: python src/feature_pipeline/run_feature_pipeline.py

      - name: Commit and Push Parquet
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/raw/*.parquet
          git commit -m "auto: update air quality data" || exit 0
          git push