name: Hourly Feature Pipeline

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests pandas pyarrow python-dotenv scikit-learn joblib

      - name: Run Pipeline, Features and Train Model
        env:
          OPENAQ_API_KEY: ${{ secrets.OPENAQ_API_KEY }}
        run: |
          python src/feature_pipeline/run_feature_pipeline.py
          python src/feature_pipeline/compute_features.py
          python src/training_pipeline/train_model.py

      - name: Commit and Push Data and Model
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Wir fügen die Daten und das Modell hinzu
          git add -f data/raw/*.parquet
          git add -f data/processed/*.parquet
          git add -f models/*.pkl
          git commit -m "auto: update data, features and model" || echo "No changes to commit"
          git push